language: r
cache: packages

r:
  - release

branches:
  only:
    - master
    - travis

sudo: false

r_packages:
  - BayesLogit

r_binary_packages:
  - coda
  - testthat
  - R.rsp
  - abind
  - ape
  - FNN
  - fields
  - ggplot2
  - MASS
  - Matrix
  - MCMCpack
  - mvtnorm
  - nnet
  - pdist
  - pROC
  - statmod
  - truncnorm

warnings_are_errors: false

r_check_revdep: false
